import{a as L,S as b,i as l}from"./assets/vendor-D9tHNiur.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const a={form:document.querySelector(".search-form"),input:document.querySelector("#input"),button:document.querySelector(".search-button"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader-box"),loadMore:document.querySelector(".load-btn")};async function v(t,o,i){const n="https://pixabay.com/api/",r={key:"49003886-a24f9c3a0fd607f8ed8b1fc56",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:i};try{return(await L.get(n,{params:r})).data}catch(s){throw console.error("Error fetching images:",s),s}}function w(t){const{largeImageURL:o,webformatURL:i,tags:n,likes:e,views:r,comments:s,downloads:y}=t;return`<li class="photo-card">
  <a class="gallery-link" href="${o}">
    <img
      class="gallery-image"
      src="${i}"
      alt="${n}"
    />
  </a>
  <div class="info">
        <p>Likes: <span class="likes">${e}</span></p>
        <p>Views: <span class="views">${r}</span></p>
        <p>Comments: <span class="comments">${s}</span></p>
        <p>Downloads: <span class="downloads">${y}</span></p>
      </div>
</li>`}const E=new b(".gallery a",{captionsData:"alt",captionDelay:250});function q(t){const o=S(t.hits);a.gallery.insertAdjacentHTML("beforeend",o),E.refresh()}function M(){a.loader.classList.remove("hidden")}function u(){a.loader.classList.add("hidden")}function R(){a.loadMore.classList.remove("hidden")}function f(){a.loadMore.classList.add("hidden")}function S(t){return t.map(w).join("")}const m=40;let d=1,p="",g=0,c=null;async function h(t){if(M(),!p){f(),l.error({title:"Error",message:"Please enter a search query.",position:"topRight"}),u();return}try{c=await v(p,d,m)}catch(o){u(),l.error({title:"Error",message:`❌ Error fetching images. Please try again ${o}`,position:"topRight",progressBar:!1}),l.error({title:"Error",message:"Failed to fetch images. Try again later!"})}finally{c.hits.length===0?l.info({title:"No Results",message:"No images found for your search.",position:"topRight",progressBar:!1}):(a.input.value="",q(c),g=c.total,P())}u()}a.form.addEventListener("submit",async t=>{t.preventDefault(),f(),p=t.target.elements.input.value.trim(),d=1,a.gallery.innerHTML="",await h()});a.loadMore.addEventListener("click",async t=>{t.preventDefault(),d+=1,await h(),B()});function B(){const o=a.gallery.firstElementChild.getBoundingClientRect().height;scrollBy({top:2*o,behavior:"smooth"})}function P(){const t=Math.ceil(g/m);d>=t?(f(),l.error({title:"Error",message:"❌ We are sorry, but you have reached the end of search results.",position:"topRight",progressBar:!1})):R()}
//# sourceMappingURL=index.js.map
