import{S as g,a as b,i as l}from"./assets/vendor-D9tHNiur.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();function v(t){const{largeImageURL:a,webformatURL:i,tags:n,likes:e,views:o,comments:s,downloads:d}=t;return`<li class="photo-card">
  <a class="gallery-link" href="${a}">
    <img
      class="gallery-image"
      src="${i}"
      alt="${n}"
    />
  </a>
  <div class="info">
        <p>Likes: <span class="likes">${e}</span></p>
        <p>Views: <span class="views">${o}</span></p>
        <p>Comments: <span class="comments">${s}</span></p>
        <p>Downloads: <span class="downloads">${d}</span></p>
      </div>
</li>`}new g(".gallery a",{captionsData:"alt",captionDelay:250});function w(){r.loader.classList.remove("hidden")}function u(){r.loader.classList.add("hidden")}function E(){r.loadMore.classList.remove("hidden")}function f(){r.loadMore.classList.add("hidden")}function q(t){return t.map(v).join("")}const r={form:document.querySelector(".search-form"),input:document.querySelector("#input"),button:document.querySelector(".search-button"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader-box"),loadMore:document.querySelector(".load-btn")},R=new g(".gallery a",{captionsData:"alt",captionDelay:250});async function S(t,a,i){const n="https://pixabay.com/api/",o={key:"49003886-a24f9c3a0fd607f8ed8b1fc56",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:a,per_page:i},{data:s,error:d}=await b.get(n,{params:o});if(d)u(),l.error({title:"Error",message:"❌ Error fetching images. Please try again!",position:"topRight",progressBar:!1});else{if(s.hits.length===0)l.info({title:"No Results",message:"No images found for your search.",position:"topRight",progressBar:!1});else{r.input.value="";const m=q(s.hits);r.gallery.insertAdjacentHTML("beforeend",m),R.refresh()}return s.total}}const h=40;let c=1,p="",y=0;async function L(t){if(w(),!p){f(),l.error({title:"Error",message:"Please enter a search query.",position:"topRight"}),u();return}y=await S(p,c,h),B(),u()}r.form.addEventListener("submit",async t=>{t.preventDefault(),f(),p=t.target.elements.input.value.trim(),c=1,r.gallery.innerHTML="",await L()});r.loadMore.addEventListener("click",async t=>{t.preventDefault(),c+=1,await L(),M()});function M(){const a=r.gallery.firstElementChild.getBoundingClientRect().height;scrollBy({top:2*a,behavior:"smooth"})}function B(){const t=Math.ceil(y/h);c>=t?(f(),l.error({title:"Error",message:"❌ We are sorry, but you have reached the end of search results.",position:"topRight",progressBar:!1})):E()}
//# sourceMappingURL=index.js.map
