import{a as b,S as v,i as l}from"./assets/vendor-D9tHNiur.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const a={form:document.querySelector(".search-form"),input:document.querySelector("#input"),button:document.querySelector(".search-button"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader-box"),loadMore:document.querySelector(".load-btn")};async function w(t,o,i){const n="https://pixabay.com/api/",r={key:"49003886-a24f9c3a0fd607f8ed8b1fc56",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:i};try{return(await b.get(n,{params:r})).data}catch(s){throw console.error("Error fetching images:",s),s}}function E(t){const{largeImageURL:o,webformatURL:i,tags:n,likes:e,views:r,comments:s,downloads:L}=t;return`<li class="photo-card">
  <a class="gallery-link" href="${o}">
    <img
      class="gallery-image"
      src="${i}"
      alt="${n}"
    />
  </a>
  <div class="info">
        <p>Likes: <span class="likes">${e}</span></p>
        <p>Views: <span class="views">${r}</span></p>
        <p>Comments: <span class="comments">${s}</span></p>
        <p>Downloads: <span class="downloads">${L}</span></p>
      </div>
</li>`}const S=new v(".gallery a",{captionsData:"alt",captionDelay:250});function q(){a.gallery.innerHTML=""}function M(t){const o=B(t.hits);a.gallery.insertAdjacentHTML("beforeend",o),S.refresh()}function R(){a.loader.classList.remove("hidden")}function f(){a.loader.classList.add("hidden")}function x(){a.loadMore.classList.remove("hidden")}function d(){a.loadMore.classList.add("hidden")}function B(t){return t.map(E).join("")}const m=40;let u=1,p="",g=0,c=null;async function h(t){R();try{c=await w(p,u,m)}catch(o){l.error({title:"Error",message:`❌ Error fetching images. Please try again ${o}`,position:"topRight",progressBar:!1}),l.error({title:"Error",message:"Failed to fetch images. Try again later!"})}finally{c.hits.length===0?l.info({title:"No Results",message:"No images found for your search.",position:"topRight",progressBar:!1}):(a.input.value="",M(c),g=c.total,$())}f()}function y(){return p?1:(d(),l.error({title:"Error",message:"Please enter a search query.",position:"topRight"}),f(),0)}a.form.addEventListener("submit",async t=>{t.preventDefault(),d(),p=t.target.elements.input.value.trim(),u=1,y()&&(q(),await h())});a.loadMore.addEventListener("click",async t=>{t.preventDefault(),u+=1,y()&&(await h(),P())});function P(){const o=a.gallery.firstElementChild.getBoundingClientRect().height;scrollBy({top:2*o,behavior:"smooth"})}function $(){const t=Math.ceil(g/m);u>=t?(d(),l.error({title:"Error",message:"❌ We are sorry, but you have reached the end of search results.",position:"topRight",progressBar:!1})):x()}
//# sourceMappingURL=index.js.map
